### ISSUE TITLE
Enable changing of latex math environment

### ISSUE THREAD

**Issue by rcst** [rcst/rim#2]
Enable replacing latex math delimiters "$$" by more space-consistent variants, e.g. "\[" or `align` environment.

**Comment by robert-dodier** [comment]
Maybe the existing functions `get_tex_environment`, `set_tex_environment`, `get_tex_environment_default`, or `set_tex_environment_default` can help here.

**Comment by rcst** [comment]
Thanks for the hint! I'll look into that.
