### ISSUE TITLE
Error with install.packages("rim")

### ISSUE THREAD

**Issue by ceworley** [rcst/rim#21]
I ran `install.packages("rim")` in the console of my local rstudio. I got an error:

```
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘rim’:
 .onAttach failed in attachNamespace() for 'rim', details:
  call: private$run()
  error: Couldn't find available port
Error: loading failed
Execution halted
ERROR: loading failed
```

I know that is not much to go on, but any ideas?

**Comment by rcst** [comment]
Hi, sorry for the delay. Can you post your `sessionInfo()`, please? Does this install from CRAN? What's your OS? 

Thanks for reporting!

**Comment by rcst** [comment]
`rim` automatically starts maxima in "server mode" and communicates with it via a socket. For this a port needs to be specified. Now, a port is chose automatically: it starts trying with port 27182 and if it isn't available, it tests the next one and so forth up until, well the end, 65536.  

Do you have a firewall that's blocking?
