### ISSUE TITLE
Make Maxima available in rim?

### ISSUE THREAD

**Issue by tontudn** [rcst/rim#23]
I installed Maxima 5.45.1 (C:\maxima-5.45.1). However, when I installed rim package to connect Maxima with R (version 4.0.2), R doesn't know where Maxima was installed? How to make Maxima available in rim?
Thank you.

**Comment by rcst** [comment]
Hi,
sorry for the late reply.
What's the specific error/ warning message that you get?

The Maxima executable needs to be installed and listed in your PATH environment variable. Can you check if that's the case?

**Comment by tontudn** [comment]
Thank for your reply.
I listed the Maxima executable in my Path  environment variable. When I typed and executed:
`library(rim)`
it executed forever.
I force to stop it (after 5 minutes for waiting), something returns like that:

 Warning: package 'rim’ was built under R version 4.0.5 
Warning in list(...) : closing unused connection 6 (<-TONTU-PC:27182) 
no loop for break/next, jumping to top level
17. initialize(...)
16. Reply$new(private$maximaSocket)
15. private$run()
14. maxima.env$maxima$start(restart)
13. maxima.start()
12. fun(libname, pkgname)
11. doTryCatch(return(expr), name, parentenv, handler)
10. tryCatchOne(expr, names, parentenv, handlers[[1L]])
9. tryCatchList(expr, classes, parentenv, handlers)
8. tryCatch(fun(libname, pkgname), error = identity)
7. runHook(".onAttach", ns, dirname(nspath), nsname)
6. attachNamespace(ns, pos = pos, deps, exclude, include.only)
5. doTryCatch(return(expr), name, parentenv, handler)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
3. tryCatchList(expr, classes, parentenv, handlers)
2. tryCatch({ attr(package, "LibPath") <- which.lib.loc ns <- loadNamespace(package, lib.loc) env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)
1. library(rim)

I check:
`rim::maxima.isInstalled()`
returns "TRUE".

`rim::maxima.version()`
returns 
Version number undetermined. Maxima needs to be running.
NULL

`rim::maxima.start(restart = TRUE)`
returns
no loop for break/next, jumping to top level
6. (function (value) { if (!missing(value)) message("Input value ignored.") ...
5. initialize(...)
4. Reply$new(private$maximaSocket)
3. private$run()
2. maxima.env$maxima$start(restart) 
1. rim::maxima.start(restart = TRUE)


`rim::maxima.get("integrate(x,x);")`
returns 
no loop for break/next, jumping to top level
7. (function (value) { if (!missing(value)) message("Input value ignored.") ...
6. initialize(...)
5. Reply$new(private$maximaSocket)
4. private$run()
3. self$start()
2. maxima.env$maxima$get(command)
1. rim::maxima.get("integrate(x,x);")


`sessionInfo()`

R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

loaded via a namespace (and not attached):
 [1] rim_0.4.1      compiler_4.0.2
 [3] magrittr_1.5   R6_2.5.1      
 [5] tools_4.0.2    Rcpp_1.0.7    
 [7] stringi_1.4.6  knitr_1.36    
 [9] stringr_1.4.0  digest_0.6.28 
[11] xfun_0.25

**Comment by rcst** [comment]
Thanks for your report and sorry for the trouble.

I think I know where this gets stuck. It has to do with how R reads from Windows' `stdout`.  Unfortunately I haven't done testing under Windows 7. I'll try to replicate the error.

Anyway, version 0.5.0 is on it's way to CRAN, you could try to update `rim` from CRAN soon, or install the latest version by `devtools::install_github("rcst/rim")` now.

I'll get back to you.

**Comment by tontudn** [comment]
I tried to do with your suggestion, but perhaps the same errors occur during the installation process.
`devtools::install_github("rcst/rim")`

Downloading GitHub repo rcst/rim@master
√  checking for file 'C:\Users\TONTU\AppData\Local\Temp\RtmpiMQSp0\remotesab4a0c378d\rcst-rim-5dd1404/DESCRIPTION'
-  preparing 'rim':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'rim_0.5.0.tar.gz'
   
* installing *source* package 'rim' ...
** using staged installation
** libs

*** arch - i386
"C:/rtools40/mingw32/bin/"g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I'C:/Program Files/R/R-4.0.2/library/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
"C:/rtools40/mingw32/bin/"g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I'C:/Program Files/R/R-4.0.2/library/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c utils.cpp -o utils.o
C:/rtools40/mingw32/bin/g++ -shared -s -static-libgcc -o rim.dll tmp.def RcppExports.o utils.o -LC:/PROGRA~1/R/R-40~1.2/bin/i386 -lR
installing to C:/Program Files/R/R-4.0.2/library/00LOCK-rim/00new/rim/libs/i386

*** arch - x64
"C:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I'C:/Program Files/R/R-4.0.2/library/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
"C:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I'C:/Program Files/R/R-4.0.2/library/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c utils.cpp -o utils.o
C:/rtools40/mingw64/bin/g++ -shared -s -static-libgcc -o rim.dll tmp.def RcppExports.o utils.o -LC:/PROGRA~1/R/R-40~1.2/bin/x64 -lR
installing to C:/Program Files/R/R-4.0.2/library/00LOCK-rim/00new/rim/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'rim'
    finding HTML links ... done
    maxima.engine                           html  
    maxima.options                          html  
    rim-package                             html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
no loop for break/next, jumping to top level
24. system2(cmd0, args, env = env, stdout = output, stderr = output, timeout = tlim)
23. i.p(...)
22. force(code)
21. force(code)
20. with_envvar(c(R_PROFILE_USER = temp_rprofile), { force(code) })
19. with_rprofile_user("options(warn = 2)", i.p(...))
18. force(code)
17. with_options(list(warn = 2), with_rprofile_user("options(warn = 2)", i.p(...)))
16. force(code)
15. with_envvar(c(R_LIBS = lib, R_LIBS_USER = lib, R_LIBS_SITE = lib, RGL_USE_NULL = "TRUE"), if (should_error_for_warnings()) { with_options(list(warn = 2), with_rprofile_user("options(warn = 2)", i.p(...))) ...
14. force(code)
13. with_options(list(install.lock = getOption("install.lock", TRUE)), { with_envvar(c(R_LIBS = lib, R_LIBS_USER = lib, R_LIBS_SITE = lib, RGL_USE_NULL = "TRUE"), if (should_error_for_warnings()) { ...
12. safe_install_packages(pkgdir, repos = NULL, quiet = quiet, type = "source", ...)
11. install(source, dependencies = dependencies, upgrade = upgrade, force = force, quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual, build_vignettes = build_vignettes, repos = repos, type = type, ...)
10. install_remote(remotes[[i]], ...)
9. doTryCatch(return(expr), name, parentenv, handler)
8. tryCatchOne(expr, names, parentenv, handlers[[1L]])
7. tryCatchList(expr, classes, parentenv, handlers)
6. tryCatch(res[[i]] <- install_remote(remotes[[i]], ...), error = function(e) { stop(remote_install_error(remotes[[i]], e)) })
5. install_remotes(remotes, auth_token = auth_token, host = host, dependencies = dependencies, upgrade = upgrade, force = force, quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual, build_vignettes = build_vignettes, repos = repos, type = type, ...
4. force(code)
3. withr::with_path(rtools_path(), code)
2. pkgbuild::with_build_tools({ ellipsis::check_dots_used(action = getOption("devtools.ellipsis_action", rlang::warn)) { ...
1. devtools::install_github("rcst/rim")

**Comment by rcst** [comment]
I was able to replicate your scenario. In short, under Windows 7 maxima seems to ignore the calling parameter `--userdir` and sets it to `%USERPROFILE%/maxima` instead. I'll consult with the Maxima folks to figure out why this happens.

`rim` sets this directory to it's own installation folder and tells maxima to initialize with two files there: `display.mac` and `display.lisp`. As a quick-fix, you can find the location of these in R: `system.file("inst/", c("display.mac", "display.lisp"), package="rim")`, create a folder in your home `C:\Users\TONTUN\maxima\` and and copy those there.

Then things should work. Can you try this?

**Comment by tontudn** [comment]
Sorry for the late reply.
Because of  unsuccessful installation of rim, these two files were not found. I got these files in your github and put them there, but it doesn't work. I try to install rim in another computer (Win 10), but the same error occurs.
It works if I put these files in `C:\Users\TONTUN\maxima\` and use `devtools::install_github("rcst/rim")` to install `rim`.
Thank you for your help.

**Comment by rcst** [comment]
I'm very sorry that `rim` caused you trouble. Glad that it works now.

This is actually a bug in Maxima. Someone from the Maxima developer team said, that this affects Win7 and Win10 likewise, just as you also found out. However, this has been fixed now. I'm waiting for a reply from them on how to get the latest version of Maxima, that includes this fix. After that, you should be able to work with `rim` from a fresh install without the need to copy any files.

**Comment by rcst** [comment]
For the sake of completeness: This has been fixed, but that doesn't mean it's been incorporated in Maxima's latest version. Two ways to update you Maxima installation with this fix are:

1. Install the latest nightly built from here: https://wolfgang.dautermann.at/maxima/nightlybuild/

or

2. Change the `c:\maxima-<version>\bin\maxima.bat` script file (with an ordinary text editor like notepad, notepad++, ...) - make a copy of the original file  before, just in case) and insert the few lines (from (https://sourceforge.net/p/maxima/code/ci/88c361) - of course without the "+" signs at the beginning).
