### ISSUE TITLE
Somehow not working

### ISSUE THREAD

**Issue by tdegold** [rcst/rim#28]
Hello. I am working with rim now for a couple of months, but this week it somehow stopped working. When I load rim and start maxima everything is fine but on execution of `maxima.get`-commands I get the following error:

```r    
> library(rim)                            
> maxima.start(restart = TRUE)
> maxima.get("1+1;")
Error in maxima.env$maxima$get(command) : lab;>>
  %o1
<<lab;
wtl;>>
  tex;>>;
$$\mathtt{(\textit{\%o}_{1})}\quad 2$$
  <<tex;
tin;>>;
$\mathtt{(\textit{\%o}_{1})}\quad 2$
  <<tin;
htm;>>
  <math xmlns="http://www.w3.org/1998/Math/MathML"> <mi>mlabel</mi>
  <mfenced separators=""><msub><mi>%o</mi> <mn>1</mn></msub>
  <mo>,</mo><mn>2</mn> </mfenced> </math>
  <<htm;
lin;>>
  (%o1) 2
<<lin;
two;>>
  (%o1)                                  2
<<two;
<<wtl;
wol;>>
  tex;>>;
Error in *alt-display2d*.
*alt-display2d* reset to default.
-- an error. To debug this try: debugmode(true);
```

If I execute `maxima.get` again I don't get the full error but still something is not working.

```r
> maxima.get("1+1;")
Error in maxima.env$maxima$get(command) : 
  (%o2)                                  2
``` 
Pretty strange that it just stopped working. Any idea what is  causing this.

Maxima version: 5.46.0

**Comment by rcst** [comment]
Hi,
thanks for reporting. What is your `sessionInfo()` output? Frankly, I haven't yet tested Maxima with 5.46.0, was it working with that version before?

**Comment by tdegold** [comment]
My` sessionInfo()` looks like this.

```R
> sessionInfo()
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_Austria.utf8  LC_CTYPE=English_Austria.utf8    LC_MONETARY=English_Austria.utf8 LC_NUMERIC=C                    
[5] LC_TIME=English_Austria.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rim_0.5.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3        digest_0.6.29       later_1.3.0         mime_0.12           R6_2.5.1            lifecycle_1.0.1    
 [7] xtable_1.8-4        jsonlite_1.8.0      magrittr_2.0.3      GlobalOptions_0.1.2 rlang_1.0.2         cli_3.3.0          
[13] promises_1.2.0.1    jquerylib_0.1.4     bslib_0.3.1         ellipsis_0.3.2      tools_4.2.0         shiny_1.7.1        
[19] xfun_0.30           httpuv_1.6.5        fastmap_1.1.0       compiler_4.2.0      pbdZMQ_0.3-7        htmltools_0.5.2    
[25] knitr_1.38          sass_0.4.1
```

It was working up until last week or the week before that. Maybe a chocolatey-update pulled the new maxima-version and broke something. I will try downgrading to 5.45.0 and let you know if it works.

**Comment by tdegold** [comment]
Yap, definitely Maxima 5.46.0 was the problem. Is downgraded to 5.45.1 and is works just fine. Seems like some communication between rim and Maxima 5.46 fails.

**Comment by rcst** [comment]
I replicated the error. Thanks.
I think it's caused by the *alt-display* package of Maxima that had undergone some changes since 5.45.0. I know where the error originates, but my understanding of Lisp (which Maxima is written in) is a bit limited.  

I've reached out to the respective Maxima developer on their mail-list, I'm sure it's easy to fix.

**Comment by rcst** [comment]
I fixed the issue you pointed out. However, with version 5.46.0 some more changes had been made, in particular how gnuplot, Maximas plotting engine, is being called, which broke some more things. So `rim`s test suite fails. I'll let you know, once I fixed that too and pushed the changes.

**Comment by rcst** [comment]
I fixed the remaining issues, it works on my machine. Could you please test on yours?
You can install the latest version from github like this

```r
remotes::install_github("rcst/rim")
```

**Comment by tdegold** [comment]
Yes! Everything works again with Maxima 5.46.0. Thank you so much! I guess we can close this issue now. 🥇
