### ISSUE TITLE
Provide interface and hanlding of `plot2d()` and `plot3d()`

### ISSUE THREAD

**Issue by rcst** [rcst/rim#3]
Provide an interface to Maxima's `plot2d()` and plot3d() enabling storing of graphics and usage in RMarkdown documents.

**Comment by robert-dodier** [comment]
This is a problem which was also handled in some way by the `maxima-jupyter` project. The way I originally implemented it (not sure if it works the same way now) is that `plot2d` inputs were recognized and changed to include arguments for output to svg or png, and then the resulting image was pasted into the display. Maybe a similar approach can help here. See: https://github.com/robert-dodier/maxima-jupyter

**Comment by rcst** [comment]
I looked into how figures are captured and pasted from regular R code chunks, I think the relevant part is [here](https://github.com/yihui/knitr/blob/cab26efb9df00b9612d67f0d88b82a767b6177e8/R/plot.R#L415-L466). For `knitr` it's impossible to automatically include figures that are not created inside R code chunks.

So I think, as you say, I would need to capture plotting calls like `plot2d` (are there other relevant functions to look for?), divert the result into a file and handover it's file path to `knitr::include_graphics()` to take care of the rest.

To go down this road, the following things need to happen:
1. capture plotting calls, change the call's options to divert output into file and get it's file path
2. call `knitr::include_graphics(path = [path-to-figure])` and append result to `ll` to be handed over in https://github.com/rcst/rim/blob/cf087f68e586aa7423ce519c5c3ca12bdbc8701f/R/engine.R#L48

**Comment by robert-dodier** [comment]
OK, terrific. About capturing output from plotting functions, there are at least two options.

(1) Redefine `plot2d` and `plot3d` (and any others we want to cover) to append an additional argument for a suitable output file type (png or svg or something), and then punt to the built-in version of the plotting function. 

This twiddle-something-and-punt approach is very easy with Lisp. I have done stuff like this many times. Something like:
```{lisp}
(let ((builtin-plot2d (symbol-function '$plot2d)))
  (defmfun $plot2d (&rest a)
    (let* 
     ((fname (mktemp-or-something))
     (b `((mlist) $svg_file ,fname)))
      (apply builtin-plot2d (append a (list b))))))
```
Load this before processing any input. Then any calls to `plot2d` will get routed through this new definition. I think `plot2d` will return the output file name (I guess we have to check that) so the caller will know afterwards where to get the file.

(2) When inputs are parsed, look for `plot2d` expressions and paste the file name into the arguments before sending them to Maxima for evaluation.

I'm inclined to try (1) first, you can let me know if you want to try it.

**Comment by rcst** [comment]
Hey Robert,

it's been a while since I had time to look into it the package and before when I had time I implemented a rather big change in the way output formats are switched and managed. 

I've started to learn lisp too and I'm now at least able to fairly understand your code draft from above. I'm also in favor of the first approach, if you could provide a sort of minimum working example, I think I'd be able to work with it/ tweak it if necessary to incorporate it.

I'd be more than happy about it, that's kind of the last issue to fix for version 0.5.0 :)

**Comment by rcst** [comment]
Oh, just if you're up to it: You could add aforementioned overrides to `inst/extdata/display.lisp`, since that's the file that automatically is loaded on startup where I also override other stuff.

Otherwise, just pasting here is fine as well.

**Comment by robert-dodier** [comment]
Hi Eric,

here's a possible implementation of a function which appends the
svg_file argument for plot2d and then calls the built-in function.

```
(defvar *builtin-plot2d* (symbol-function 'plot2d-impl))

($set_random_state ($make_random_state ($absolute_real_time)))

(defmfun $plot2d (&rest args)
  (if (member '$svg_file args)
    ;; Hmm. plot2d args already contains svg_file.
    ;; Just punt the call without modifying the arguments.
    (apply *builtin-plot2d* args)
    ;; Otherwise, append another argument for svg_file,
    ;; and then punt to built-in plot2d.
    (let*
      ((nnn (+ ($random 900000) 100000))
       (svg-file ($sconcat $maxima_tempdir "/plot2d-" nnn ".svg"))
       (args-new (append args (list `((mlist) $svg_file ,svg-file)))))
      (format t "plot2d: append svg file ~s to arguments and call
built-in plot2d.~%" svg-file)
      (format t "plot2d: new args: ~a~%" (mfuncall '$string `((mlist)
***@***.***)))
      (apply *builtin-plot2d* args-new))))
```

Put that in a file and load it via load("myfile.lisp");
and then try something like: plot2d(sin(x), [x, -5, 5]);
You should find that plot2d says something about the svg file and does
not display a plot. You should be able to use the file in another
program.

The file name is generated at random, according to the template
plot2d-nnnnnn.svg. Probably better to call Unix mktemp but it may be a
low priority item to fix it. We can cross that bridge when we come to
it.

Give it a try and let me know how it works!

Robert

**Comment by rcst** [comment]
Thank you Robert!

I copied the lines from above into `plot.lisp` and however then in maxima

```
Maxima 5.44.0 http://maxima.sourceforge.net
using Lisp GNU Common Lisp (GCL) GCL 2.6.12
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
prompt;>>(%i1) <<prompt;load("plot.lisp");

loadfile: failed to load plot.lisp
 -- an error. To debug this try: debugmode(true);
prompt;>>(%i2) <<prompt;
```

When I don't quote the file name I get a more specific error code:

```
prompt;>>(%i2) <<prompt;load(plot.lisp);

Maxima encountered a Lisp error:

 Condition in MACSYMA-TOP-LEVEL [or a callee]: INTERNAL-SIMPLE-TYPE-ERROR: ((MNCTIMES
                                                                             SIMP)
                                                                            $PLOT
                                                                            $LISP) is not of type STRING: 

Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.
prompt;>>(%i3) <<prompt;
```
Did I do something wrong?

I tried to understand this error, but my knowledge of lisp does not yet cover macros, which I think is involved here.

Eric

**Comment by robert-dodier** [comment]
Hi Eric, I see some problems which you can try fixing.

(1) try saving your Lisp file as something other than plot.lisp since plot.lisp is the name of one of the built-in Lisp files. How about myplot.lisp or something like that.

(2) try loading the file via `?load("myplot.lisp");` (which loads it via the Lisp input reader, so you'll get a more detailed error message) instead of `load("myplot.lisp");`. If there is no error, then `load("myplot.lisp");` is just as good.

(3) It looks like the code got messed up by the message formatting system. Let me try to paste it again. Try this instead.

```{common-lisp}
(defvar *builtin-plot2d* (symbol-function 'plot2d-impl))

($set_random_state ($make_random_state ($absolute_real_time)))

(defmfun $plot2d (&rest args)
  (if (member '$svg_file args)
    ;; Hmm. plot2d args already contains svg_file.
    ;; Just punt the call without modifying the arguments.
    (apply *builtin-plot2d* args)
    ;; Otherwise, append another argument for svg_file,
    ;; and then punt to built-in plot2d.
    (let*
      ((nnn (+ ($random 900000) 100000))
       (svg-file ($sconcat $maxima_tempdir "/plot2d-" nnn ".svg"))
       (args-new (append args (list `((mlist) $svg_file ,svg-file)))))
      (format t "plot2d: append svg file ~s to arguments and call
built-in plot2d.~%" svg-file)
      (format t "plot2d: new args: ~a~%" (mfuncall '$string (cons '(mlist) new-args)))
      (apply *builtin-plot2d* args-new))))
```

**Comment by rcst** [comment]
OK, now I could fix it.

There were only two things: `(symbol-function '$plot2d-impl)` and `... (cons '(mlist) args-new` instead of the above.

**Comment by rcst** [comment]
Now that I'm thinking about it more thoroughly, there are two issues that I didn't consider:

1. files that are saved into `maxima_tempdir`, at least under Debian, persist, if not explicitly removed.
2. For html-based output formats `knitr` creates a folder next to the source RMarkdown file named `[source-file]-files` in the same directory as the source file, where plots are stored, because unlike for pdf documents, images are not embedded into, html files.
3. Hence, I'm thinking that instead of saving maxima plots into `maxima_tempdir`, they should be put into the `[source-file]-files` directory.

Does maxima keep a variable of the directory it was called from? I searched the documentation, but didn't find anything.

Modification of the arguments of `plot2d()` could also be done on the R side, before it's sent to maxima. From there I know, what's the current directory, but I don't have a strong view on that. What do you think?

**Comment by robert-dodier** [comment]
Hi Eric, looks like the current (5.45 and later, I think; maybe 5.44, not sure) `plot2d` writes the output file into `maxima_tempdir` only if there is no directory specified in the output file name. So e.g. "foo.svg" goes into `maxima_tempdir`, but `./foo.svg` goes into the current working directory (more about this below), and `/tmp/foo.svg` goes into `/tmp`, and `mumble/blurf/foo.svg` goes into `mumble/blurf` in the current working directory.

So one way I can see to direct output into `somefolder-files` is to have a variable which can be set by whoever is calling `plot2d`, and then concatenate that variable with the randomly generated file name. Something like:
```
(defvar $plot2d_output_folder ".") ;; by default, denotes the current working directory
```
and then later on
```
      (svg-file ($sconcat $plot2d_output_folder "/plot2d-" nnn ".svg"))
```
About the current working directory, the one that counts is the cwd for gnuplot when gnuplot is executed by Maxima. To be honest, I don't know how that is determined. If it turns out that gnuplot's idea of the cwd doesn't align with what you need it to be, you could work around the problem by supply an absolute path for `plot2d_output_folder`, e.g. `/home/robert/documents/somedocument-files`.

By the way, the Lisp variable `$plot2d_output_folder` is referenced in Maxima as just `plot2d_output_folder`; all Lisp variables beginning with dollar sign are like that. In Lisp code, you include the dollar sign.

**Comment by rcst** [comment]
OK, for `plot2d()` and `plot3d()` this is working now. Some minor changes to the approach are:

- plots are saved in the same directory as the Rmd file
- the file name contains the first 6 digits of the sha256sum of the concatenated string "plot2d"/ "plot3d" and all arguments to avoid creating same files with different file names.

To do:
- depending on output format (PDF or HTML) the plots should be saved as PDF or PNG, respectively. By doing so, we can use `knitr::include_graphics("[plot-name].png", auto_pdf = TRUE)`. The output format can be determined from within the engine `knitr::is_html_output()` and/ or `knitr::is_latex_output()` and an appropriate preload file can be chosen.
- implement the same for strategy for other plotting functions (which?)

**Comment by robert-dodier** [comment]
Hi Eric, all that sounds good, glad to hear you got it working.

About other plotting functions, you could try covering `draw` / `draw2d` / `draw3d` which are pretty widely used. There are a few other plotting functions, `implicit_plot`, `contour_plot`, and `plotdf`, maybe others. The good news is that `implicit_plot` and `contour_plot` have been reimplemented via `plot2d`, so I don't think you need to try to cover them. How about just covering the `draw` functions.

**Comment by rcst** [comment]
@robert-dodier 

I'm tackling the `draw` family of functions. From reading the Maxima manual, I understand that both `draw2d()` and `draw3d()` eventually call `draw()`, so that I'd only have to overwrite `draw()` to divert the output into a file.

I understand that the format of the arguments to draw differs from the ones of e.g. `plot2d()`.

In code for `plot2d()` the new argument takes the form of `plot2d(..., [pdf_file, "plot2d-123456.pdf"])`. For `draw()` however we need `draw(..., file_name = "./draw-123456.pdf")`

Once again my knowledge of Lisp is missing. I guess I need to look at this in the first case: `(list '((mlist) $file_name, file_name))`. What does the function `mlist` do?

From what I understand, I want to construct the unevaluated expression in Maxima `filename = "draw-123456.pdf"`
I tried (among others): `(list '(= $file_name filename))`, but the resulting error tells that `file_name` is not a number, which means that `=` strangely gets evaluated. Happy about your hints to solve this myself.

**Comment by robert-dodier** [comment]
Hi Eric, the Maxima expression `file_name = "foobar.pdf"` is represented as the Lisp expression `((mequal) $file_name "foobar.pdf")`. Note that the first element in the list `(mequal)` , which corresponds to the operator in the Maxima expression, is not the name of a function; Maxima doesn't require that operators be actual functions, operators can be just formal placeholders.

To create such an expression is a little tricky. I assume `filename` is the Lisp variable which holds `"foobar.pdf"` or whatever. If so, then `(list '(mlist) '$file_name filename)` should do it. Note carefully the single quote mark before `(mlist)` and the single quote before `$file_name` -- these are crucial. 

A good way to see the Lisp representation of an expression is to say `:lisp $%` after computing something in Maxima (maybe I mentioned that already).

**Comment by rcst** [comment]
@robert-dodier Thanks for the hints, I strangely enjoy learning lisp this way.

Now, I'm having a challenge with `plotdf` that you mentioned. I couldn't find in the documentation where it mentions a parameter to save the plot as a file, besides clicking the "save" button in the corresponding plotting window. Any hints? Is this possible?

**Comment by robert-dodier** [comment]
Glad to hear this process works for you!

`plotdf` is a Tcl-only plotter -- I don't think you can use it to make image files.

**Comment by rcst** [comment]
OK.

I'd need the `draw` family of functions to return (instead of printing) a string containing the file name that the plot was saved as. (`plod2d` and `plot3d` always return a list containing this, e.g. `[/tmp/maxout13276.gnuplot, ./plot3d-ea8c4c.pdf]` by themselves, `draw` etc. doesn't)

`(format NIL "~a" file_name)`

doesn't seem to return anything in Maxima. Is there a special Maxima stream object or something that I should provide? Or how can I do this?

**Comment by robert-dodier** [comment]
About `draw` functions, it looks like `draw` has less machinery around output file names. If you supply `foo.baz` as an output file name, it gets written into the Gnuplot command file just like that, and (I'm pretty sure but could be mistaken) that file is created in the current working directory when Gnuplot is executed.

It's too bad that `draw` doesn't return the file name, but I think we can arrange it so that the location of the file is predictable. How do you want it to work? Into what directory do you want output images to go?

By the way, in what way is the current behavior of `draw` not working for you?

**Comment by rcst** [comment]
Nevermind, it was actually working, also because I now know how to build a list `((mlist)...)` and return that.
(the rather stupid error was that I was testing it with suppressed commands e.g. `draw(...)$`, pretty embarrassing).
