### ISSUE TITLE
Reset line numers

### ISSUE THREAD

**Issue by sebastian-gerdes** [rcst/rim#31]
Dear all,

I really like the possiblity to include maxima in quarto documents - thank you very much for the package.

Since I am moving code chunks around quite a bit with more ore less independent calculations it would be nice to be able to reset the linenumbers (%o1, %o2 etc.) / delete %o1, %o2 etc? 

Or maybe to restart the maxima session?

To make it more clear have a look at the following gist:
https://gist.github.com/sebastian-gerdes/dc02620a1890041e45dfcdd494802e45

Thanks and best greetings,
Sebastian

**Comment by rcst** [comment]
Hi Sebastian,

glad you find it useful.

This is essentially a Maxima question. Currently restarting the Maxima session of the knitr engine is not implemented, but possible to do. However, if it is just about the reference labels themselves, restarting is not necessary - just reset the label counter yourself 

`maxima.get("x^2 = 2, linenum:1, %)$")` (or `x^2 = 2, linenum:1, %)$` code chunk)

This will run `x^2 = 2` and assign the result to `%o1`.

**Comment by sebastian-gerdes** [comment]
Hi Eric,

thanks you are answering even though it is more of a Maxima question.

Unfortunately, both code snippets above produce errors on my system.
"Error in maxima.env$maxima$get(command) : incorrect syntax: Too many )'s 2 = 2, linenum:1, %)"

When I try `maxima.get("x^2 = 2, linenum: 3;")`, the output number is not updated as desired.

If you know why it is not working - great - if not - I can live with the numbering as it is, I just have to be a bit careful when moving code chunks around!

Thanks a lot and best greetings!
Sebastian

**Comment by sebastian-gerdes** [comment]
Hi Eric,

actually `maxima.start(restart = TRUE)` does the job for me as I want it to! I don't know why I hadn't found this option before. 

Best greetings,
Sebastian

**Comment by rcst** [comment]
Sorry, my fault, there is a typo, the opening bracket is missing, try

```r
maxima.get("(x^2 = 2, linenum: 1, %)$")
```

This essentially runs three commands in a block-like fashion as a single command, ending a command with `$` surpresses the output. Again, this should be better than a complete restart.

**Comment by sebastian-gerdes** [comment]
Thanks, now it works!
