### ISSUE TITLE
Path issue when running R CMD check

### ISSUE THREAD

**Issue by ltierney** [rcst/rim#36]
Running R CMD check in a particular directory setup on Fedora 38 the check failed with an error that can be reproduced with this code:

```r
library(rim)
d <- "/tmp/scratch2/luke/R-devel/CRAN/check/rim.Rcheck/rim/extdata"
dir.create(d, recursive = TRUE)
file.copy(system.file("extdata", "test.Rmd", package = "rim"), d)
fr <- paste0(d, "/test.Rmd")
fo <- paste0(dirname(fr[1]), "/test.md")
knitr::knit(input = fr[1], output = fo, quiet = TRUE)
unlink("/tmp/scratch2", recursive = TRUE)
```
The `knitr` messages are:

```
Quitting from lines 52-54 [unnamed-chunk-9] (/tmp/scratch2/luke/R-devel/CRAN/check/rim.Rcheck/rim/extdata/test.Rmd)
Error in `knitr::include_graphics()`:
! Cannot find the file(s): "/tmp/scratch2/luke/R-devel/CRAN/check/rim.Rch\eck/rim/extdata/plot2d-95d531.png"
Backtrace:
  1. knitr::knit(input = fr[1], output = fo, quiet = TRUE)
  2. knitr:::process_file(text, output)
  6. knitr:::process_group.block(group)
  7. knitr:::call_block(x)
  8. knitr:::block_exec(params)
 11. rim (local) engine(options)
 13. knitr::include_graphics(pm, rel_path = FALSE)
Warning message:
In normalizePath(pm) :
  path[1]="/tmp/scratch2/luke/R-devel/CRAN/check/rim.Rch\eck/rim/extdata/plot2d-95d531.png": No such file or directory
```
Note the stray backslash in the path. I don't see this issue with the knitr R engine so I'm guessing it is in your `maxima.engine`, but I didn't explore further.

**Comment by rcst** [comment]
Thanks for reporting! This seems to coincide with the CRAN [check failures](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/rim-00check.html) for Fedora R-devel

I replicated the error under Fedora 36 R-devel.

Could you please try the above again with the latest changes from this repo? Many thanks!

**Comment by ltierney** [comment]
The new version passes `R CMD check` run in the directory where it previously failed.
