### ISSUE TITLE
Error on installing from source

### ISSUE THREAD

**Issue by pvermees** [rcst/rim#38]
`rim` fails to install on my system (Ubuntu 22.04, R 4.1.2.) using both CRAN and GitHub, because of the presence of lone underscores on lines 77, 89 and 100 of `R/engin.utils.R`. Replacing these with acceptable inputs fixes the issue.

**Comment by rcst** [comment]
Thanks for flagging this. The functions in those lines make use of the `|>` (pipe) operator in conjunction with the `_`  placeholder that was introduced in R 4.2.0 (Apr 22, 2022). I see that `rim` doesn't state a minimum R version required.

I will revert this to conventional syntax for backwards compatibility.

**Comment by rcst** [comment]
[d113376](https://github.com/rcst/rim/commit/d1133760c89ab443e2e04838eb78c54e198206aa)
