### ISSUE TITLE
Knitr Engine Throws Error when Solving Rational Inequalities by fourier_elim

### ISSUE THREAD

**Issue by HankNu** [rcst/rim#46]
I can solve this inequality in Xmaxima.

```
load("fourier_elim");
fourier_elim([x^2-1>0],[x]);
(%o1) /usr/local/share/maxima/5.47.0/share/fourier_elim/fourier_elim.lisp
(%i2) 
(%o2)                        [1 < x] or [x < - 1]
```

Then  I try to test this route with rim in R.

```{r}
library(rim)
maxima.start()
maxima.version()
```

But `fourier_elim`cannot be knitted,

```{maxima fourier_elim_0,eval=T}
load("fourier_elim");
```

```{maxima fourier_elim_1,eval=F}
load("fourier_elim");
fourier_elim([x^2-1>0],[x]);
```

which throw the error as below:

```
[fourier_elim_1]     Error in `if (grepl("no-convert", p <- private$reply$result$wol$rstr)) ...`:
! the condition has length > 1
Backtrace:
  1. rmarkdown::render(...)
  2. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  3. knitr:::process_file(text, output)
  6. knitr:::process_group(group)
  7. knitr:::call_block(x)
  8. knitr:::block_exec(params)
 11. rim (local) engine(options)
 12. maxima.env$mx$get(pc)
                                                                                                                
Warning message:
In maxima.env$mx$get(pc) : WARNING: redefining BIGFLOAT::WHILE in DEFMACRO

Quitting from lines 701-703 [fourier_elim_1] (rim123.Rmd)
Execution halted
```

Then I find that `solve_rat_ineq` can be knitted well.

```{maxima solve_rat_ineq}
load(solve_rat_ineq);
solve_rat_ineq(x^2-1>0);
```

My environment is 

```{r}
sessionInfo()
maxima.version()
```

There is some other inequalities to be tested.

```{maxima fourier_elim_2,eval=F}
fourier_elim((x + y < 5) and (x - y >8),[x,y]);
fourier_elim(((x + y < 5) and x < 1) or (x - y >8),[x,y]);
```

**Comment by HankNu** [comment]
I guess it is because the output of  `fourier_elim` can not be done with by rim, e.g.
```
(%i1) load(solve_rat_ineq);
solve_rat_ineq(x^2-1>0);
(%o1) /usr/local/share/maxima/5.47.0/share/solve_rat_ineq/solve_rat_ineq.mac
(%i2) 
(%o2)                        [[x < - 1], [x > 1]]
(%i3) load("fourier_elim");
fourier_elim([x^2-1>0],[x]);
(%o3) /usr/local/share/maxima/5.47.0/share/fourier_elim/fourier_elim.lisp
(%i4) 
(%o4)                        [1 < x] or [x < - 1]
```
As we can see, the first output (%o2) is a list [[x < - 1], [x > 1]], but the second output (%o4)   is a string [1 < x] or [x < - 1].

**Comment by HankNu** [comment]
[Uploading fourier_elim_test.pdf…]()

**Comment by HankNu** [comment]
This is the PDF output of my Rmd.
 
[fourier_elim_test.pdf](https://github.com/user-attachments/files/17092254/fourier_elim_test.pdf)

**Comment by rcst** [comment]
Thanks for reporting. That should be easy to fix, the error comes from a failing check whether the returned result from Maxima was successfully parsed into R code. I'll have a go at this by the end of this week.

**Comment by HankNu** [comment]
rim is an excellent job to connect Maxima and R. Thanks a lot.

**Comment by rcst** [comment]
I pushed a fix, your example now works. Can you test?

**Comment by HankNu** [comment]
> I pushed a fix, your example now works. Can you test?

After upgrade to packageVersion('rim')=0.7.0, everything is OK. Thanks for your job.
[fourier_elim_test-20241021.pdf](https://github.com/user-attachments/files/17456153/fourier_elim_test-20241021.pdf)
